services:
  db:
    image: postgres:18
    container_name: postgres_rutas
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: "fas23??¿¿adJoseph"
      POSTGRES_DB: rutas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
